### ISSUE TITLE
Module does not seem to respond correctly after wakeup from sleep

### ISSUE THREAD

**Issue by fiskfan** [RAKWireless/RAK811#1]
Working with the RAK811 module and i think i have found an issue.

If i put the module to sleep with "at+sleep" then i get an "OK" response back. If i then try to wake it by sending a command - for eaxmple "at+version" - or anything else then i get the "at+recv=8,0,0" response back that indicates that the module is back from sleep.

However, after this the module seems unresponsive... After I received the at+recv=8,0,0 response then it appears to stop responding to any commands. I cannot put it to sleep and not wake it with any command i have tried so far. Only way to get it resonding again is to reset power.

Any one else who has noticed this issue?

**Comment by RAKWireless** [comment]
Yes, we have noticed this problem and we will fix this in the AT firmware that will be updated later.
