### ISSUE TITLE
Documentation or firmware error?

### ISSUE THREAD

**Issue by rogerdahl** [RAKWireless/RAK811#3]
In `RAK811 LoRa AT Command v1.4.pdf`:

```
<ch_mask>:<id>,<mask>

The ch_mask can configure fast choose which channels will be used as uplink
channel by default.
<id>: id=0, channel 0-15 for region, id = 1 means 16-31 ,etc ...
<mask>: as hex, 0003 means use channel 0, 1 .
For example Region US915_CH0-7, should set id 0 mask 00FF, id 1 mask 0, id 2
mask 0, id 3 mask 0, id 4 mask 0
```

AT command output (setting unmodified from factory on my US915 module):

```
at+get_config=ch_mask
OK0,ffff;1,ffff;2,ffff;3,ffff;4,00ff␍␊
```

So:

- IDs are in reverse order from documentation
- Values that doc says should be 0000 are ffff

Which is correct?

I also found that updating these values simultaneously does not work:

```
at+get_config=ch_mask
OK0,ffff;1,ffff;2,ffff;3,ffff;4,00ff
at+set_config=ch_mask:0,ffff;1,ffff;2,ffff;3,ffff;4,00ff
ERROR-1
```

However, updating them individually does work:

```
at+set_config=ch_mask:0,ffff
```

**Comment by rogerdahl** [comment]
Also, if I write the values back as they were first retrieved, the module hangs on OTAA:

```
at+set_config=ch_mask:0,ffff
at+set_config=ch_mask:1,ffff
at+set_config=ch_mask:2,ffff
at+set_config=ch_mask:3,ffff
at+set_config=ch_mask:4,00ff
at+mode=0
at+join=otaa

-> hang, with module continuously using around 20mA
```

**Comment by RAKWireless** [comment]
There is no error in the documentation, it may be that you understand the error, LoRaWAN defaults to 72 channels are open. However, the gateway can only have a maximum of 8 channels. Therefore, the US915 needs to set the ch_mask.

**Comment by rogerdahl** [comment]
Thank you for the explanation. I think that resolves the first issue, but not the second.

If you try running the `at+set_config` commands I listed, I think you will find that the module becomes unresponsive after the `at+join`.
