### ISSUE TITLE
Outdated, incomplete datasheet

### ISSUE THREAD

**Issue by rogerdahl** [RAKWireless/RAK811#4]
The datasheet on GitHub is `RAK811 LoRa Module Datasheet V1.1.pdf` while v1.3 is available on wiki.rakwireless.com.

Neither datasheets say which version of STM32L151 is used in the module.

The schematic, `RAK811 SCH.pdf` also does not state version of STM32L151.

The amount of available flash memory seems to be undocumented. STM32L151 comes with anything from 32 to 512 KiB.

**Comment by RAKWireless** [comment]
Is STM32L151CB
